apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 32080
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  containers:
  - name: front-end
    image: agray998/front-end:latest
    ports:
    - containerPort: 5000
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "supersecretpassword!"
