apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  type: NodePort  # set the type of Service
  selector:
    app: nginx-demo    # referencing the Pod's label
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32080
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo    # needs to be the same as Service's selector
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
